# Generated by Django 4.1.7 on 2024-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASH_pillars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='basicneedsupport',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hardship',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
