# Generated by Django 4.1.7 on 2024-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASH_pillars', '0002_delete_event_alter_basicneedsupport_name_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('nuid', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=50)),
                ('is_dash_member', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('basic_need_supports', models.ManyToManyField(blank=True, to='DASH_pillars.basicneedsupport')),
                ('hardships', models.ManyToManyField(blank=True, to='DASH_pillars.hardship')),
                ('scholarships', models.ManyToManyField(blank=True, to='DASH_pillars.scholarship')),
            ],
        ),
    ]
