# Generated by Django 4.1.7 on 2024-08-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deactivated_at',
        ),
    ]
