# Generated by Django 4.1.7 on 2024-07-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='nuid',
            new_name='NUID',
        ),
    ]
