# Generated by Django 4.1.7 on 2024-08-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reason_for_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason_For_Visit',
        ),
    ]
