# Generated by Django 4.1.7 on 2024-07-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_nuid_student_nuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('nuid', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role_within_dash', models.CharField(max_length=50)),
                ('edits_made', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
