# Generated by Django 4.1.7 on 2024-08-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_reason_for_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.BooleanField(default=False)),
                ('printing', models.BooleanField(default=False)),
                ('study', models.BooleanField(default=False)),
                ('socialize', models.BooleanField(default=False)),
                ('event', models.BooleanField(default=False)),
                ('schedule_appointment', models.BooleanField(default=False)),
                ('hardship', models.BooleanField(default=False)),
                ('basic_needs_support', models.BooleanField(default=False)),
                ('financial_wellness', models.BooleanField(default=False)),
                ('volunteer_opportunities', models.BooleanField(default=False)),
            ],
        ),
    ]
