# Generated by Django 4.1.7 on 2024-07-31 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='nuid',
            new_name='NUID',
        ),
    ]
