# Generated by Django 4.1.7 on 2024-07-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_nuid_admin_nuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='NUID',
            field=models.CharField(max_length=20),
        ),
    ]
