# Generated by Django 4.1.7 on 2024-07-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_nuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='NUID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
